// Generated by @adddog/monorepo-consistency
// Do not edit manually - regenerate with: mono knip generate
import type { KnipConfig } from "knip";

export default {
    $schema: "https://unpkg.com/knip@6/schema.json",
    treatConfigHintsAsErrors: false,
    eslint: false,
    project: ["src/**/*.ts"],
    ignoreDependencies: [
        "@adddog/zod-to-json-schema",
    ],
    ignoreBinaries: [
        "gh",
    ],
} satisfies KnipConfig;
