// Generated by @adddog/monorepo-consistency
// Do not edit manually - regenerate with: pnpm generate:knip
import { defineKnipConfig } from "@adddog/monorepo-consistency";

export default defineKnipConfig({
    entry: ["src/index.ts", "src/cli.ts", "bin/*.{ts,js}"],
    project: ["src/**/*.ts", "bin/**/*.{ts,js}"],
    ignore: [
        // Test fixtures and helpers - used by vitest
        "tests/**",
    ],
});
